name: Auto Submit Areen

on:
    schedule:
    - cron: '0 4,16 * * *'  # تشغيل الساعة 7 صباحًا و7 مساءً بتوقيت القدس (UTC+3)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run script
        run: node script.js

      - name: Upload result artifact
        uses: actions/upload-artifact@v4
        with:
          name: result-log
          path: result.txt
